import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'about',
    {
      type: 'category',
      label: 'Концепции',
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: 'Инструменты',
      items: ['tools/index', 'tools/ide', 'tools/cli', 'tools/llm', 'tools/mcp', 'tools/services'],
    },
    {
      type: 'category',
      label: 'Инструменты (все)',
      className: 'tools-sidebar-hidden',
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },
    {
      type: 'category',
      label: 'Воркфлоу',
      items: [{type: 'autogenerated', dirName: 'workflows'}],
    },
    {
      type: 'category',
      label: 'Мини-аппы',
      items: [{type: 'autogenerated', dirName: 'apps'}],
    },
    {
      type: 'category',
      label: 'Сообщество',
      items: [{type: 'autogenerated', dirName: 'community'}],
    },
    {
      type: 'category',
      label: 'Meta',
      items: [{type: 'autogenerated', dirName: 'meta'}],
    },
    {
      type: 'category',
      label: 'Ссылки',
      items: [{type: 'autogenerated', dirName: 'links'}],
    },
    {
      type: 'category',
      label: 'Справочные материалы',
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Статьи',
      items: [{type: 'autogenerated', dirName: 'articles'}],
    },
    {
      type: 'category',
      label: 'Остальное',
      items: [{type: 'autogenerated', dirName: 'misc'}],
    },
    {
      type: 'category',
      label: 'Docusaurus',
      items: [
        {type: 'autogenerated', dirName: 'tutorial-basics'},
        {type: 'autogenerated', dirName: 'tutorial-extras'},
      ],
    },
  ],
};

export default sidebars;
